### ISSUE TITLE
dasboard

### ISSUE THREAD

**Issue by JARWATI** [travis-ci/beta-features#9] opened 2017-03-14 21:48 UTC

**Comment by nickmccurdy** [comment] 2017-03-14 22:28
Is this a duplicate of #5?

**Comment by JARWATI** [comment] 2017-03-14 23:12
Yes on dasboard issue

**Comment by joshk** [comment] 2017-03-15 00:03
Hi @JARWATI 

Please use the issues listed in https://github.com/travis-ci/beta-features/issues for commenting on Beta Features. 

I am closing this thread.

Thanks

Josh

**Closed by joshk** 2017-03-15 00:03 UTC
